# -*- coding: utf-8 -*-
"""Native UI string patches for sync_ui_strings.py."""

NEW_EN = {
    "favorites_title": "MY FAVORITES",
    "search_short_placeholder": "Search...",
    "btn_study": "STUDY",
    "cd_clear": "Clear",
    "favorites_empty_title": "No favorites yet",
    "favorites_empty_search_title": "No results found",
    "favorites_empty_desc": "Add words you like here to study them later.",
    "favorites_empty_search_desc": "No favorite word matched your search.",
    "cd_delete": "Delete",
    "learning_no_favorites_title": "No favorites yet",
    "learning_no_favorites_message": "Add some words to favorites from the dictionary to use flashcards.",
    "learning_cards_title": "Flashcards",
    "learning_word_label": "WORD",
    "learning_synonym_label": "SYNONYM",
    "learning_finish": "FINISH",
    "learning_next_word": "NEXT WORD",
    "learning_flip_hint": "Tap the card to flip it.",
    "loading_subtitle": "Loading words...",
    "cd_close": "Close",
    "cd_add_word": "Add word",
    "cd_settings": "Settings",
    "mode_hint_title": "You can switch dictionary",
    "mode_hint_body": "Switch between synonyms, verbs, idioms and more. Words not found locally are searched on TDK automatically.",
    "mode_hint_ok": "Got it",
    "menu_show_daily_word": "Show word of the day",
    "share_word_title": "Share word",
    "word_tree_title": "WORD TREE",
    "cd_reset": "Reset",
    "cd_favorite": "Favorite",
    "cd_listen": "Listen",
    "cd_share": "Share",
    "cd_speak": "Read aloud",
    "cd_voice_search": "Voice search",
    "voice_search_prompt": "Say a word...",
    "weekly_last_7_days": "Last 7 days",
    "day_mon": "Mon",
    "day_tue": "Tue",
    "day_wed": "Wed",
    "day_thu": "Thu",
    "day_fri": "Fri",
    "day_sat": "Sat",
    "day_sun": "Sun",
    "day_mon_full": "Monday",
    "day_tue_full": "Tuesday",
    "day_wed_full": "Wednesday",
    "day_thu_full": "Thursday",
    "day_fri_full": "Friday",
    "day_sat_full": "Saturday",
    "day_sun_full": "Sunday",
    "notification_channel_name": "Word of the day",
    "notification_title": "Word of the day: %1$s",
    "notification_body": "Synonym: %1$s. Learn now!",
    "share_mode_verbs": "meaning",
    "share_mode_definitions": "definition",
    "share_mode_idioms": "meaning",
    "share_mode_adjectives": "meaning",
    "share_mode_all": "meaning/synonym"
}

CD_OPEN_MENU = {
    "tr": "Menüyü aç",
    "en": "Open menu",
    "de": "Menü öffnen",
    "az": "Menyunu aç",
    "kk": "Мәзірді ашу",
    "ky": "Менуну ачуу",
    "uz": "Menyuni ochish",
    "tk": "Menýany aç",
    "ru": "Открыть меню",
    "ar": "فتح القائمة",
    "fr": "Ouvrir le menu",
    "es": "Abrir menú",
    "pt": "Abrir menu",
    "hi": "मेनू खोलें",
    "bn": "মেনু খুলুন",
    "ur": "مینو کھولیں",
    "id": "Buka menu",
    "ja": "メニューを開く",
    "ko": "메뉴 열기",
    "zh-CN": "打开菜单",
    "vi": "Mở menu",
    "ta": "மெனுவைத் திற",
    "te": "మెనూ తెరవండి",
    "mr": "मेनू उघडा",
    "sw": "Fungua menyu",
}

LOCALE_PATCHES = {
    "en": {
        "favorites_title": "MY FAVORITES",
        "search_short_placeholder": "Search...",
        "btn_study": "STUDY",
        "cd_clear": "Clear",
        "favorites_empty_title": "No favorites yet",
        "favorites_empty_search_title": "No results found",
        "favorites_empty_desc": "Add words you like here to study them later.",
        "favorites_empty_search_desc": "No favorite word matched your search.",
        "cd_delete": "Delete",
        "learning_no_favorites_title": "No favorites yet",
        "learning_no_favorites_message": "Add some words to favorites from the dictionary to use flashcards.",
        "learning_cards_title": "Flashcards",
        "learning_word_label": "WORD",
        "learning_synonym_label": "SYNONYM",
        "learning_finish": "FINISH",
        "learning_next_word": "NEXT WORD",
        "learning_flip_hint": "Tap the card to flip it.",
        "loading_subtitle": "Loading words...",
        "cd_close": "Close",
        "cd_add_word": "Add word",
        "cd_settings": "Settings",
        "mode_hint_title": "You can switch dictionary",
        "mode_hint_body": "Switch between synonyms, verbs, idioms and more. Words not found locally are searched on TDK automatically.",
        "mode_hint_ok": "Got it",
        "menu_show_daily_word": "Show word of the day",
        "share_word_title": "Share word",
        "word_tree_title": "WORD TREE",
        "cd_reset": "Reset",
        "cd_favorite": "Favorite",
        "cd_listen": "Listen",
        "cd_share": "Share",
        "cd_speak": "Read aloud",
        "cd_voice_search": "Voice search",
        "voice_search_prompt": "Say a word...",
        "weekly_last_7_days": "Last 7 days",
        "day_mon": "Mon",
        "day_tue": "Tue",
        "day_wed": "Wed",
        "day_thu": "Thu",
        "day_fri": "Fri",
        "day_sat": "Sat",
        "day_sun": "Sun",
        "day_mon_full": "Monday",
        "day_tue_full": "Tuesday",
        "day_wed_full": "Wednesday",
        "day_thu_full": "Thursday",
        "day_fri_full": "Friday",
        "day_sat_full": "Saturday",
        "day_sun_full": "Sunday",
        "notification_channel_name": "Word of the day",
        "notification_title": "Word of the day: %1$s",
        "notification_body": "Synonym: %1$s. Learn now!",
        "share_mode_verbs": "meaning",
        "share_mode_definitions": "definition",
        "share_mode_idioms": "meaning",
        "share_mode_adjectives": "meaning",
        "share_mode_all": "meaning/synonym"
    },
    "tr": {
        "favorites_title": "FAVORİLERİM",
        "search_short_placeholder": "Ara...",
        "btn_study": "ÇALIŞ",
        "cd_clear": "Temizle",
        "favorites_empty_title": "Henüz Favoriniz Yok",
        "favorites_empty_search_title": "Sonuç Bulunamadı",
        "favorites_empty_desc": "Beğendiğiniz kelimeleri buraya ekleyerek daha sonra çalışabilirsiniz.",
        "favorites_empty_search_desc": "Aramanızla eşleşen bir favori kelime bulamadık.",
        "cd_delete": "Sil",
        "learning_no_favorites_title": "Henüz Favori Yok",
        "learning_no_favorites_message": "Kelime kartlarını kullanabilmek için önce sözlükten bazı kelimeleri favorilerinize eklemelisiniz.",
        "learning_cards_title": "Kelime Kartları",
        "learning_word_label": "KELİME",
        "learning_synonym_label": "EŞ ANLAMLISI",
        "learning_finish": "BİTİR",
        "learning_next_word": "SIRADAKİ KELİME",
        "learning_flip_hint": "Kartı çevirmek için üzerine dokunun.",
        "loading_subtitle": "Kelimeler hazırlanıyor...",
        "cd_close": "Kapat",
        "cd_add_word": "Kelime Ekle",
        "cd_settings": "Ayarlar",
        "mode_hint_title": "Sözlüğü değiştirebilirsin",
        "mode_hint_body": "Buradan Fiiller, Eş Anlamlılar, Deyimler gibi sözlük modları arasında geçiş yapabilirsin. Yerelde bulunamayan kelimeleri de otomatik olarak TDK'dan aratırız.",
        "mode_hint_ok": "Anladım",
        "menu_show_daily_word": "Günün Kelimesini Göster",
        "share_word_title": "Kelimeyi Paylaş",
        "word_tree_title": "KELİME AĞACI",
        "cd_reset": "Sıfırla",
        "cd_favorite": "Favori",
        "cd_listen": "Dinle",
        "cd_share": "Paylaş",
        "cd_speak": "Sesli oku",
        "cd_voice_search": "Sesli Ara",
        "voice_search_prompt": "Bir kelime söyleyin...",
        "weekly_last_7_days": "Son 7 gün",
        "day_mon": "Pzt",
        "day_tue": "Sal",
        "day_wed": "Çar",
        "day_thu": "Per",
        "day_fri": "Cum",
        "day_sat": "Cmt",
        "day_sun": "Paz",
        "day_mon_full": "Pazartesi",
        "day_tue_full": "Salı",
        "day_wed_full": "Çarşamba",
        "day_thu_full": "Perşembe",
        "day_fri_full": "Cuma",
        "day_sat_full": "Cumartesi",
        "day_sun_full": "Pazar",
        "notification_channel_name": "Günün Kelimesi",
        "notification_title": "Günün Kelimesi: %1$s",
        "notification_body": "Eş anlamlısı: %1$s. Hemen öğren!",
        "share_mode_verbs": "anlamı",
        "share_mode_definitions": "tanımı",
        "share_mode_idioms": "anlamı",
        "share_mode_adjectives": "anlamı",
        "share_mode_all": "anlamı/eş anlamlısı"
    },
    "de": {
        "favorites_title": "MEINE FAVORITEN",
        "search_short_placeholder": "Suchen...",
        "btn_study": "LERNEN",
        "cd_clear": "Löschen",
        "favorites_empty_title": "Noch keine Favoriten",
        "favorites_empty_search_title": "Keine Ergebnisse",
        "favorites_empty_desc": "Fügen Sie Wörter hinzu, um sie später zu lernen.",
        "favorites_empty_search_desc": "Kein Favorit entspricht Ihrer Suche.",
        "cd_delete": "Löschen",
        "learning_no_favorites_title": "Noch keine Favoriten",
        "learning_no_favorites_message": "Fügen Sie zuerst Wörter aus dem Wörterbuch zu Favoriten hinzu.",
        "learning_cards_title": "Lernkarten",
        "learning_word_label": "WORT",
        "learning_synonym_label": "GLEICHBEDEUTEND",
        "learning_finish": "FERTIG",
        "learning_next_word": "NÄCHSTES WORT",
        "learning_flip_hint": "Tippen Sie auf die Karte, um sie umzudrehen.",
        "loading_subtitle": "Wörter werden geladen...",
        "cd_close": "Schließen",
        "cd_add_word": "Wort hinzufügen",
        "cd_settings": "Einstellungen",
        "mode_hint_title": "Wörterbuch wechseln",
        "mode_hint_body": "Wechseln Sie zwischen Synonymen, Verben, Redewendungen und mehr. Nicht lokale Wörter werden automatisch bei TDK gesucht.",
        "mode_hint_ok": "Verstanden",
        "menu_show_daily_word": "Wort des Tages anzeigen",
        "share_word_title": "Wort teilen",
        "word_tree_title": "WORTBAUM",
        "cd_reset": "Zurücksetzen",
        "cd_favorite": "Favorit",
        "cd_listen": "Anhören",
        "cd_share": "Teilen",
        "cd_speak": "Vorlesen",
        "cd_voice_search": "Sprachsuche",
        "voice_search_prompt": "Sagen Sie ein Wort...",
        "weekly_last_7_days": "Letzte 7 Tage",
        "day_mon": "Mo",
        "day_tue": "Di",
        "day_wed": "Mi",
        "day_thu": "Do",
        "day_fri": "Fr",
        "day_sat": "Sa",
        "day_sun": "So",
        "day_mon_full": "Montag",
        "day_tue_full": "Dienstag",
        "day_wed_full": "Mittwoch",
        "day_thu_full": "Donnerstag",
        "day_fri_full": "Freitag",
        "day_sat_full": "Samstag",
        "day_sun_full": "Sonntag",
        "notification_channel_name": "Wort des Tages",
        "notification_title": "Wort des Tages: %1$s",
        "notification_body": "Synonym: %1$s. Jetzt lernen!",
        "share_mode_verbs": "Bedeutung",
        "share_mode_definitions": "Definition",
        "share_mode_idioms": "Bedeutung",
        "share_mode_adjectives": "Bedeutung",
        "share_mode_all": "Bedeutung/Synonym"
    },
    "ar": {
        "favorites_title": "المفضلة",
        "search_short_placeholder": "بحث...",
        "btn_study": "دراسة",
        "cd_clear": "مسح",
        "favorites_empty_title": "لا توجد مفضلة بعد",
        "favorites_empty_search_title": "لم يتم العثور على نتائج",
        "favorites_empty_desc": "أضف الكلمات التي تعجبك هنا لدراستها لاحقًا.",
        "favorites_empty_search_desc": "لم تطابق أي كلمة مفضلة بحثك.",
        "cd_delete": "حذف",
        "learning_no_favorites_title": "لا توجد مفضلة بعد",
        "learning_no_favorites_message": "أضف بعض الكلمات إلى المفضلة من القاموس لاستخدام البطاقات التعليمية.",
        "learning_cards_title": "بطاقات تعليمية",
        "learning_word_label": "كلمة",
        "learning_synonym_label": "مرادف",
        "learning_finish": "إنهاء",
        "learning_next_word": "الكلمة التالية",
        "learning_flip_hint": "اضغط على البطاقة لقلبها.",
        "loading_subtitle": "جارٍ تحميل الكلمات...",
        "cd_close": "إغلاق",
        "cd_add_word": "إضافة كلمة",
        "cd_settings": "الإعدادات",
        "mode_hint_title": "يمكنك تبديل القاموس",
        "mode_hint_body": "التبديل بين المرادفات والأفعال والتعابير والمزيد. الكلمات غير الموجودة محليًا تُبحث في TDK تلقائيًا.",
        "mode_hint_ok": "فهمت",
        "menu_show_daily_word": "عرض كلمة اليوم",
        "share_word_title": "مشاركة الكلمة",
        "word_tree_title": "شجرة الكلمات",
        "cd_reset": "إعادة تعيين",
        "cd_favorite": "مفضلة",
        "cd_listen": "استماع",
        "cd_share": "مشاركة",
        "cd_speak": "قراءة بصوت",
        "cd_voice_search": "بحث صوتي",
        "voice_search_prompt": "قل كلمة...",
        "weekly_last_7_days": "آخر 7 أيام",
        "day_mon": "إث",
        "day_tue": "ثل",
        "day_wed": "أر",
        "day_thu": "خم",
        "day_fri": "جم",
        "day_sat": "سب",
        "day_sun": "أح",
        "day_mon_full": "الاثنين",
        "day_tue_full": "الثلاثاء",
        "day_wed_full": "الأربعاء",
        "day_thu_full": "الخميس",
        "day_fri_full": "الجمعة",
        "day_sat_full": "السبت",
        "day_sun_full": "الأحد",
        "notification_channel_name": "كلمة اليوم",
        "notification_title": "كلمة اليوم: %1$s",
        "notification_body": "مرادف: %1$s. تعلّم الآن!",
        "share_mode_verbs": "المعنى",
        "share_mode_definitions": "التعريف",
        "share_mode_idioms": "المعنى",
        "share_mode_adjectives": "المعنى",
        "share_mode_all": "المعنى/المرادف"
    },
    "az": {
        "favorites_title": "SEÇİLMİŞLƏRİM",
        "search_short_placeholder": "Axtar...",
        "btn_study": "ÖYRƏN",
        "cd_clear": "Təmizlə",
        "favorites_empty_title": "Hələ seçilmiş yoxdur",
        "favorites_empty_search_title": "Nəticə tapılmadı",
        "favorites_empty_desc": "Bəyəndiyiniz sözləri buraya əlavə edərək sonra öyrənə bilərsiniz.",
        "favorites_empty_search_desc": "Axtarışınıza uyğun seçilmiş söz tapılmadı.",
        "cd_delete": "Sil",
        "learning_no_favorites_title": "Hələ seçilmiş yoxdur",
        "learning_no_favorites_message": "Kartlardan istifadə etmək üçün əvvəlcə lüğətdən bəzi sözləri seçilmişlərə əlavə edin.",
        "learning_cards_title": "Söz kartları",
        "learning_word_label": "SÖZ",
        "learning_synonym_label": "EYNİ MƏNALI",
        "learning_finish": "BİTİR",
        "learning_next_word": "NÖVBƏTİ SÖZ",
        "learning_flip_hint": "Kartı çevirmək üçün üzərinə toxunun.",
        "loading_subtitle": "Sözlər hazırlanır...",
        "cd_close": "Bağla",
        "cd_add_word": "Söz əlavə et",
        "cd_settings": "Parametrlər",
        "mode_hint_title": "Lüğəti dəyişdirə bilərsiniz",
        "mode_hint_body": "Sinonimlər, fellər, deyimlər və s. arasında keçid edin. Yerli bazada tapılmayan sözlər avtomatik TDK-da axtarılır.",
        "mode_hint_ok": "Anladım",
        "menu_show_daily_word": "Günün sözünü göstər",
        "share_word_title": "Sözü paylaş",
        "word_tree_title": "SÖZ AĞACI",
        "cd_reset": "Sıfırla",
        "cd_favorite": "Seçilmiş",
        "cd_listen": "Dinlə",
        "cd_share": "Paylaş",
        "cd_speak": "Səsli oxu",
        "cd_voice_search": "Səsli axtar",
        "voice_search_prompt": "Bir söz deyin...",
        "weekly_last_7_days": "Son 7 gün",
        "day_mon": "B.e.",
        "day_tue": "Ç.a.",
        "day_wed": "Ç.",
        "day_thu": "C.a.",
        "day_fri": "C.",
        "day_sat": "Ş.",
        "day_sun": "B.",
        "day_mon_full": "Bazar ertəsi",
        "day_tue_full": "Çərşənbə axşamı",
        "day_wed_full": "Çərşənbə",
        "day_thu_full": "Cümə axşamı",
        "day_fri_full": "Cümə",
        "day_sat_full": "Şənbə",
        "day_sun_full": "Bazar",
        "notification_channel_name": "Günün sözü",
        "notification_title": "Günün sözü: %1$s",
        "notification_body": "Eyni mənalı: %1$s. İndi öyrən!",
        "share_mode_verbs": "mənası",
        "share_mode_definitions": "tərifi",
        "share_mode_idioms": "mənası",
        "share_mode_adjectives": "mənası",
        "share_mode_all": "mənası/eyni mənalı"
    },
    "bn": {
        "favorites_title": "আমার প্রিয়",
        "search_short_placeholder": "অনুসন্ধান...",
        "btn_study": "অধ্যয়ন",
        "cd_clear": "মুছুন",
        "favorites_empty_title": "এখনও কোনো প্রিয় নেই",
        "favorites_empty_search_title": "কোনো ফলাফল পাওয়া যায়নি",
        "favorites_empty_desc": "পছন্দের শব্দগুলো এখানে যোগ করুন, পরে অধ্যয়ন করতে পারবেন।",
        "favorites_empty_search_desc": "আপনার অনুসন্ধানের সাথে কোনো প্রিয় শব্দ মিলেনি।",
        "cd_delete": "মুছুন",
        "learning_no_favorites_title": "এখনও কোনো প্রিয় নেই",
        "learning_no_favorites_message": "ফ্ল্যাশকার্ড ব্যবহার করতে অভিধান থেকে কিছু শব্দ প্রিয় তালিকায় যোগ করুন।",
        "learning_cards_title": "ফ্ল্যাশকার্ড",
        "learning_word_label": "শব্দ",
        "learning_synonym_label": "প্রতিশব্দ",
        "learning_finish": "শেষ",
        "learning_next_word": "পরের শব্দ",
        "learning_flip_hint": "কার্ড উল্টাতে এতে ট্যাপ করুন।",
        "loading_subtitle": "শব্দ লোড হচ্ছে...",
        "cd_close": "বন্ধ",
        "cd_add_word": "শব্দ যোগ করুন",
        "cd_settings": "সেটিংস",
        "mode_hint_title": "আপনি অভিধান পরিবর্তন করতে পারেন",
        "mode_hint_body": "প্রতিশব্দ, ক্রিয়া, প্রবাদ ইত্যাদির মধ্যে পরিবর্তন করুন। স্থানীয়ভাবে না পাওয়া শব্দ স্বয়ংক্রিয়ভাবে TDK-তে খোঁজা হয়।",
        "mode_hint_ok": "বুঝেছি",
        "menu_show_daily_word": "আজকের শব্দ দেখান",
        "share_word_title": "শব্দ শেয়ার করুন",
        "word_tree_title": "শব্দ বৃক্ষ",
        "cd_reset": "রিসেট",
        "cd_favorite": "প্রিয়",
        "cd_listen": "শুনুন",
        "cd_share": "শেয়ার",
        "cd_speak": "জোরে পড়ুন",
        "cd_voice_search": "ভয়েস অনুসন্ধান",
        "voice_search_prompt": "একটি শব্দ বলুন...",
        "weekly_last_7_days": "গত ৭ দিন",
        "day_mon": "সোম",
        "day_tue": "মঙ্গ",
        "day_wed": "বুধ",
        "day_thu": "বৃহ",
        "day_fri": "শুক্র",
        "day_sat": "শনি",
        "day_sun": "রবি",
        "day_mon_full": "সোমবার",
        "day_tue_full": "মঙ্গলবার",
        "day_wed_full": "বুধবার",
        "day_thu_full": "বৃহস্পতিবার",
        "day_fri_full": "শুক্রবার",
        "day_sat_full": "শনিবার",
        "day_sun_full": "রবিবার",
        "notification_channel_name": "আজকের শব্দ",
        "notification_title": "আজকের শব্দ: %1$s",
        "notification_body": "প্রতিশব্দ: %1$s. এখনই শিখুন!",
        "share_mode_verbs": "অর্থ",
        "share_mode_definitions": "সংজ্ঞা",
        "share_mode_idioms": "অর্থ",
        "share_mode_adjectives": "অর্থ",
        "share_mode_all": "অর্থ/প্রতিশব্দ"
    },
    "es": {
        "favorites_title": "MIS FAVORITOS",
        "search_short_placeholder": "Buscar...",
        "btn_study": "ESTUDIAR",
        "cd_clear": "Borrar",
        "favorites_empty_title": "Aún no hay favoritos",
        "favorites_empty_search_title": "No se encontraron resultados",
        "favorites_empty_desc": "Añade aquí las palabras que te gusten para estudiarlas después.",
        "favorites_empty_search_desc": "Ninguna palabra favorita coincide con tu búsqueda.",
        "cd_delete": "Eliminar",
        "learning_no_favorites_title": "Aún no hay favoritos",
        "learning_no_favorites_message": "Añade palabras a favoritos desde el diccionario para usar las tarjetas.",
        "learning_cards_title": "Tarjetas",
        "learning_word_label": "PALABRA",
        "learning_synonym_label": "SINÓNIMO",
        "learning_finish": "FINALIZAR",
        "learning_next_word": "SIGUIENTE PALABRA",
        "learning_flip_hint": "Toca la tarjeta para voltearla.",
        "loading_subtitle": "Cargando palabras...",
        "cd_close": "Cerrar",
        "cd_add_word": "Añadir palabra",
        "cd_settings": "Ajustes",
        "mode_hint_title": "Puedes cambiar de diccionario",
        "mode_hint_body": "Cambia entre sinónimos, verbos, modismos y más. Las palabras no encontradas localmente se buscan en TDK automáticamente.",
        "mode_hint_ok": "Entendido",
        "menu_show_daily_word": "Mostrar palabra del día",
        "share_word_title": "Compartir palabra",
        "word_tree_title": "ÁRBOL DE PALABRAS",
        "cd_reset": "Restablecer",
        "cd_favorite": "Favorito",
        "cd_listen": "Escuchar",
        "cd_share": "Compartir",
        "cd_speak": "Leer en voz alta",
        "cd_voice_search": "Búsqueda por voz",
        "voice_search_prompt": "Di una palabra...",
        "weekly_last_7_days": "Últimos 7 días",
        "day_mon": "Lun",
        "day_tue": "Mar",
        "day_wed": "Mié",
        "day_thu": "Jue",
        "day_fri": "Vie",
        "day_sat": "Sáb",
        "day_sun": "Dom",
        "day_mon_full": "Lunes",
        "day_tue_full": "Martes",
        "day_wed_full": "Miércoles",
        "day_thu_full": "Jueves",
        "day_fri_full": "Viernes",
        "day_sat_full": "Sábado",
        "day_sun_full": "Domingo",
        "notification_channel_name": "Palabra del día",
        "notification_title": "Palabra del día: %1$s",
        "notification_body": "Sinónimo: %1$s. ¡Aprende ahora!",
        "share_mode_verbs": "significado",
        "share_mode_definitions": "definición",
        "share_mode_idioms": "significado",
        "share_mode_adjectives": "significado",
        "share_mode_all": "significado/sinónimo"
    },
    "fr": {
        "favorites_title": "MES FAVORIS",
        "search_short_placeholder": "Rechercher...",
        "btn_study": "ÉTUDIER",
        "cd_clear": "Effacer",
        "favorites_empty_title": "Pas encore de favoris",
        "favorites_empty_search_title": "Aucun résultat",
        "favorites_empty_desc": "Ajoutez ici les mots que vous aimez pour les étudier plus tard.",
        "favorites_empty_search_desc": "Aucun mot favori ne correspond à votre recherche.",
        "cd_delete": "Supprimer",
        "learning_no_favorites_title": "Pas encore de favoris",
        "learning_no_favorites_message": "Ajoutez des mots aux favoris depuis le dictionnaire pour utiliser les cartes.",
        "learning_cards_title": "Cartes mémoire",
        "learning_word_label": "MOT",
        "learning_synonym_label": "SYNONYME",
        "learning_finish": "TERMINER",
        "learning_next_word": "MOT SUIVANT",
        "learning_flip_hint": "Appuyez sur la carte pour la retourner.",
        "loading_subtitle": "Chargement des mots...",
        "cd_close": "Fermer",
        "cd_add_word": "Ajouter un mot",
        "cd_settings": "Paramètres",
        "mode_hint_title": "Vous pouvez changer de dictionnaire",
        "mode_hint_body": "Passez des synonymes aux verbes, expressions et plus. Les mots absents localement sont recherchés automatiquement sur TDK.",
        "mode_hint_ok": "Compris",
        "menu_show_daily_word": "Afficher le mot du jour",
        "share_word_title": "Partager le mot",
        "word_tree_title": "ARBRE DE MOTS",
        "cd_reset": "Réinitialiser",
        "cd_favorite": "Favori",
        "cd_listen": "Écouter",
        "cd_share": "Partager",
        "cd_speak": "Lire à voix haute",
        "cd_voice_search": "Recherche vocale",
        "voice_search_prompt": "Dites un mot...",
        "weekly_last_7_days": "7 derniers jours",
        "day_mon": "Lun",
        "day_tue": "Mar",
        "day_wed": "Mer",
        "day_thu": "Jeu",
        "day_fri": "Ven",
        "day_sat": "Sam",
        "day_sun": "Dim",
        "day_mon_full": "Lundi",
        "day_tue_full": "Mardi",
        "day_wed_full": "Mercredi",
        "day_thu_full": "Jeudi",
        "day_fri_full": "Vendredi",
        "day_sat_full": "Samedi",
        "day_sun_full": "Dimanche",
        "notification_channel_name": "Mot du jour",
        "notification_title": "Mot du jour : %1$s",
        "notification_body": "Synonyme : %1$s. Apprenez maintenant !",
        "share_mode_verbs": "signification",
        "share_mode_definitions": "définition",
        "share_mode_idioms": "signification",
        "share_mode_adjectives": "signification",
        "share_mode_all": "signification/synonyme"
    },
    "hi": {
        "favorites_title": "मेरे पसंदीदा",
        "search_short_placeholder": "खोजें...",
        "btn_study": "अध्ययन",
        "cd_clear": "साफ़ करें",
        "favorites_empty_title": "अभी कोई पसंदीदा नहीं",
        "favorites_empty_search_title": "कोई परिणाम नहीं मिला",
        "favorites_empty_desc": "पसंद के शब्द यहाँ जोड़ें, बाद में अध्ययन कर सकेंगे।",
        "favorites_empty_search_desc": "आपकी खोज से कोई पसंदीदा शब्द मेल नहीं खाया।",
        "cd_delete": "हटाएँ",
        "learning_no_favorites_title": "अभी कोई पसंदीदा नहीं",
        "learning_no_favorites_message": "फ्लैशकार्ड के लिए शब्दकोश से कुछ शब्द पसंदीदा में जोड़ें।",
        "learning_cards_title": "फ्लैशकार्ड",
        "learning_word_label": "शब्द",
        "learning_synonym_label": "पर्यायवाची",
        "learning_finish": "समाप्त",
        "learning_next_word": "अगला शब्द",
        "learning_flip_hint": "कार्ड पलटने के लिए उस पर टैप करें।",
        "loading_subtitle": "शब्द लोड हो रहे हैं...",
        "cd_close": "बंद करें",
        "cd_add_word": "शब्द जोड़ें",
        "cd_settings": "सेटिंग्स",
        "mode_hint_title": "आप शब्दकोश बदल सकते हैं",
        "mode_hint_body": "पर्यायवाची, क्रियाएँ, मुहावरे आदि के बीच स्विच करें। स्थानीय रूप से न मिले शब्द TDK में स्वतः खोजे जाते हैं।",
        "mode_hint_ok": "समझ गया",
        "menu_show_daily_word": "आज का शब्द दिखाएँ",
        "share_word_title": "शब्द साझा करें",
        "word_tree_title": "शब्द वृक्ष",
        "cd_reset": "रीसेट",
        "cd_favorite": "पसंदीदा",
        "cd_listen": "सुनें",
        "cd_share": "साझा करें",
        "cd_speak": "ज़ोर से पढ़ें",
        "cd_voice_search": "आवाज़ खोज",
        "voice_search_prompt": "कोई शब्द बोलें...",
        "weekly_last_7_days": "पिछले 7 दिन",
        "day_mon": "सोम",
        "day_tue": "मंग",
        "day_wed": "बुध",
        "day_thu": "गुरु",
        "day_fri": "शुक्र",
        "day_sat": "शनि",
        "day_sun": "रवि",
        "day_mon_full": "सोमवार",
        "day_tue_full": "मंगलवार",
        "day_wed_full": "बुधवार",
        "day_thu_full": "गुरुवार",
        "day_fri_full": "शुक्रवार",
        "day_sat_full": "शनिवार",
        "day_sun_full": "रविवार",
        "notification_channel_name": "आज का शब्द",
        "notification_title": "आज का शब्द: %1$s",
        "notification_body": "पर्यायवाची: %1$s. अभी सीखें!",
        "share_mode_verbs": "अर्थ",
        "share_mode_definitions": "परिभाषा",
        "share_mode_idioms": "अर्थ",
        "share_mode_adjectives": "अर्थ",
        "share_mode_all": "अर्थ/पर्यायवाची"
    },
    "id": {
        "favorites_title": "FAVORIT SAYA",
        "search_short_placeholder": "Cari...",
        "btn_study": "BELAJAR",
        "cd_clear": "Hapus",
        "favorites_empty_title": "Belum ada favorit",
        "favorites_empty_search_title": "Tidak ada hasil",
        "favorites_empty_desc": "Tambahkan kata favorit di sini untuk dipelajari nanti.",
        "favorites_empty_search_desc": "Tidak ada kata favorit yang cocok dengan pencarian Anda.",
        "cd_delete": "Hapus",
        "learning_no_favorites_title": "Belum ada favorit",
        "learning_no_favorites_message": "Tambahkan kata dari kamus ke favorit untuk menggunakan kartu flash.",
        "learning_cards_title": "Kartu flash",
        "learning_word_label": "KATA",
        "learning_synonym_label": "SINONIM",
        "learning_finish": "SELESAI",
        "learning_next_word": "KATA BERIKUTNYA",
        "learning_flip_hint": "Ketuk kartu untuk membaliknya.",
        "loading_subtitle": "Memuat kata...",
        "cd_close": "Tutup",
        "cd_add_word": "Tambah kata",
        "cd_settings": "Pengaturan",
        "mode_hint_title": "Anda dapat mengganti kamus",
        "mode_hint_body": "Beralih antara sinonim, kata kerja, idiom, dan lainnya. Kata yang tidak ditemukan secara lokal dicari di TDK secara otomatis.",
        "mode_hint_ok": "Mengerti",
        "menu_show_daily_word": "Tampilkan kata hari ini",
        "share_word_title": "Bagikan kata",
        "word_tree_title": "POHON KATA",
        "cd_reset": "Atur ulang",
        "cd_favorite": "Favorit",
        "cd_listen": "Dengarkan",
        "cd_share": "Bagikan",
        "cd_speak": "Baca keras",
        "cd_voice_search": "Pencarian suara",
        "voice_search_prompt": "Ucapkan kata...",
        "weekly_last_7_days": "7 hari terakhir",
        "day_mon": "Sen",
        "day_tue": "Sel",
        "day_wed": "Rab",
        "day_thu": "Kam",
        "day_fri": "Jum",
        "day_sat": "Sab",
        "day_sun": "Min",
        "day_mon_full": "Senin",
        "day_tue_full": "Selasa",
        "day_wed_full": "Rabu",
        "day_thu_full": "Kamis",
        "day_fri_full": "Jumat",
        "day_sat_full": "Sabtu",
        "day_sun_full": "Minggu",
        "notification_channel_name": "Kata hari ini",
        "notification_title": "Kata hari ini: %1$s",
        "notification_body": "Sinonim: %1$s. Belajar sekarang!",
        "share_mode_verbs": "arti",
        "share_mode_definitions": "definisi",
        "share_mode_idioms": "arti",
        "share_mode_adjectives": "arti",
        "share_mode_all": "arti/sinonim"
    },
    "ja": {
        "favorites_title": "お気に入り",
        "search_short_placeholder": "検索...",
        "btn_study": "学習",
        "cd_clear": "クリア",
        "favorites_empty_title": "お気に入りはまだありません",
        "favorites_empty_search_title": "結果が見つかりません",
        "favorites_empty_desc": "気に入った単語をここに追加して、後で学習できます。",
        "favorites_empty_search_desc": "検索に一致するお気に入りの単語がありません。",
        "cd_delete": "削除",
        "learning_no_favorites_title": "お気に入りはまだありません",
        "learning_no_favorites_message": "フラッシュカードを使うには、辞書から単語をお気に入りに追加してください。",
        "learning_cards_title": "フラッシュカード",
        "learning_word_label": "単語",
        "learning_synonym_label": "同義語",
        "learning_finish": "終了",
        "learning_next_word": "次の単語",
        "learning_flip_hint": "カードをタップして裏返します。",
        "loading_subtitle": "単語を読み込み中...",
        "cd_close": "閉じる",
        "cd_add_word": "単語を追加",
        "cd_settings": "設定",
        "mode_hint_title": "辞書を切り替えられます",
        "mode_hint_body": "同義語、動詞、慣用句などを切り替えられます。ローカルにない単語はTDKで自動検索されます。",
        "mode_hint_ok": "了解",
        "menu_show_daily_word": "今日の単語を表示",
        "share_word_title": "単語を共有",
        "word_tree_title": "単語ツリー",
        "cd_reset": "リセット",
        "cd_favorite": "お気に入り",
        "cd_listen": "聴く",
        "cd_share": "共有",
        "cd_speak": "読み上げ",
        "cd_voice_search": "音声検索",
        "voice_search_prompt": "単語を話してください...",
        "weekly_last_7_days": "過去7日間",
        "day_mon": "月",
        "day_tue": "火",
        "day_wed": "水",
        "day_thu": "木",
        "day_fri": "金",
        "day_sat": "土",
        "day_sun": "日",
        "day_mon_full": "月曜日",
        "day_tue_full": "火曜日",
        "day_wed_full": "水曜日",
        "day_thu_full": "木曜日",
        "day_fri_full": "金曜日",
        "day_sat_full": "土曜日",
        "day_sun_full": "日曜日",
        "notification_channel_name": "今日の単語",
        "notification_title": "今日の単語: %1$s",
        "notification_body": "同義語: %1$s. 今すぐ学ぼう!",
        "share_mode_verbs": "意味",
        "share_mode_definitions": "定義",
        "share_mode_idioms": "意味",
        "share_mode_adjectives": "意味",
        "share_mode_all": "意味/同義語"
    },
    "kk": {
        "favorites_title": "ТАҢДАУЛЫЛАРЫМ",
        "search_short_placeholder": "Іздеу...",
        "btn_study": "ҮЙРЕНУ",
        "cd_clear": "Тазалау",
        "favorites_empty_title": "Әлі таңдаулы жоқ",
        "favorites_empty_search_title": "Нәтиже табылмады",
        "favorites_empty_desc": "Ұнатқан сөздеріңізді осында қосып, кейін оқи аласыз.",
        "favorites_empty_search_desc": "Іздеуіңізге сәйкес таңдаулы сөз табылмады.",
        "cd_delete": "Жою",
        "learning_no_favorites_title": "Әлі таңдаулы жоқ",
        "learning_no_favorites_message": "Карталарды пайдалану үшін алдымен сөздіктен сөздерді таңдаулыға қосыңыз.",
        "learning_cards_title": "Сөз карталары",
        "learning_word_label": "СӨЗ",
        "learning_synonym_label": "СИНОНИМ",
        "learning_finish": "АЯҚТАУ",
        "learning_next_word": "КЕЛЕСІ СӨЗ",
        "learning_flip_hint": "Картаны аудару үшін оған басыңыз.",
        "loading_subtitle": "Сөздер дайындалуда...",
        "cd_close": "Жабу",
        "cd_add_word": "Сөз қосу",
        "cd_settings": "Баптаулар",
        "mode_hint_title": "Сөздікті ауыстыра аласыз",
        "mode_hint_body": "Синонимдер, етістіктер, мақал-мәтелдер және т.б. арасында ауысыңыз. Жергілікті базада жоқ сөздер TDK-да автоматты ізделеді.",
        "mode_hint_ok": "Түсіндім",
        "menu_show_daily_word": "Күн сөзін көрсету",
        "share_word_title": "Сөзді бөлісу",
        "word_tree_title": "СӨЗ АҒАШЫ",
        "cd_reset": "Қайта орнату",
        "cd_favorite": "Таңдаулы",
        "cd_listen": "Тыңдау",
        "cd_share": "Бөлісу",
        "cd_speak": "Дауыспен оқу",
        "cd_voice_search": "Дауыс іздеу",
        "voice_search_prompt": "Сөз айтыңыз...",
        "weekly_last_7_days": "Соңғы 7 күн",
        "day_mon": "Дс",
        "day_tue": "Сс",
        "day_wed": "Ср",
        "day_thu": "Бс",
        "day_fri": "Жм",
        "day_sat": "Сб",
        "day_sun": "Жс",
        "day_mon_full": "Дүйсенбі",
        "day_tue_full": "Сейсенбі",
        "day_wed_full": "Сәрсенбі",
        "day_thu_full": "Бейсенбі",
        "day_fri_full": "Жұма",
        "day_sat_full": "Сенбі",
        "day_sun_full": "Жексенбі",
        "notification_channel_name": "Күн сөзі",
        "notification_title": "Күн сөзі: %1$s",
        "notification_body": "Синоним: %1$s. Қазір үйрен!",
        "share_mode_verbs": "мағынасы",
        "share_mode_definitions": "анықтaması",
        "share_mode_idioms": "мағынасы",
        "share_mode_adjectives": "мағынасы",
        "share_mode_all": "мағынасы/синоним"
    },
    "ko": {
        "favorites_title": "즐겨찾기",
        "search_short_placeholder": "검색...",
        "btn_study": "학습",
        "cd_clear": "지우기",
        "favorites_empty_title": "아직 즐겨찾기 없음",
        "favorites_empty_search_title": "결과 없음",
        "favorites_empty_desc": "좋아하는 단어를 여기에 추가해 나중에 학습하세요.",
        "favorites_empty_search_desc": "검색과 일치하는 즐겨찾기 단어가 없습니다.",
        "cd_delete": "삭제",
        "learning_no_favorites_title": "아직 즐겨찾기 없음",
        "learning_no_favorites_message": "플래시카드를 사용하려면 사전에서 단어를 즐겨찾기에 추가하세요.",
        "learning_cards_title": "플래시카드",
        "learning_word_label": "단어",
        "learning_synonym_label": "동의어",
        "learning_finish": "완료",
        "learning_next_word": "다음 단어",
        "learning_flip_hint": "카드를 탭하여 뒤집으세요.",
        "loading_subtitle": "단어 불러오는 중...",
        "cd_close": "닫기",
        "cd_add_word": "단어 추가",
        "cd_settings": "설정",
        "mode_hint_title": "사전을 전환할 수 있습니다",
        "mode_hint_body": "동의어, 동사, 관용구 등을 전환하세요. 로컬에 없는 단어는 TDK에서 자동 검색됩니다.",
        "mode_hint_ok": "알겠습니다",
        "menu_show_daily_word": "오늘의 단어 표시",
        "share_word_title": "단어 공유",
        "word_tree_title": "단어 트리",
        "cd_reset": "초기화",
        "cd_favorite": "즐겨찾기",
        "cd_listen": "듣기",
        "cd_share": "공유",
        "cd_speak": "읽어주기",
        "cd_voice_search": "음성 검색",
        "voice_search_prompt": "단어를 말하세요...",
        "weekly_last_7_days": "최근 7일",
        "day_mon": "월",
        "day_tue": "화",
        "day_wed": "수",
        "day_thu": "목",
        "day_fri": "금",
        "day_sat": "토",
        "day_sun": "일",
        "day_mon_full": "월요일",
        "day_tue_full": "화요일",
        "day_wed_full": "수요일",
        "day_thu_full": "목요일",
        "day_fri_full": "금요일",
        "day_sat_full": "토요일",
        "day_sun_full": "일요일",
        "notification_channel_name": "오늘의 단어",
        "notification_title": "오늘의 단어: %1$s",
        "notification_body": "동의어: %1$s. 지금 배우세요!",
        "share_mode_verbs": "의미",
        "share_mode_definitions": "정의",
        "share_mode_idioms": "의미",
        "share_mode_adjectives": "의미",
        "share_mode_all": "의미/동의어"
    },
    "ky": {
        "favorites_title": "ТАНДАЛГАНДАРЫМ",
        "search_short_placeholder": "Издөө...",
        "btn_study": "ҮЙРӨН",
        "cd_clear": "Тазалоо",
        "favorites_empty_title": "Али тандалган жок",
        "favorites_empty_search_title": "Натыйжа табылган жок",
        "favorites_empty_desc": "Жаккан сөздөрүңүздү бул жерге кошуп, кийин окуй аласыз.",
        "favorites_empty_search_desc": "Издөөңүзгө дал келген тандалган сөз табылган жок.",
        "cd_delete": "Өчүрүү",
        "learning_no_favorites_title": "Али тандалган жок",
        "learning_no_favorites_message": "Карталарды колдонуу үчүн алды менен сөздүктөн сөздөрдү тандалгандарга кошуңуз.",
        "learning_cards_title": "Сөз карталары",
        "learning_word_label": "СӨЗ",
        "learning_synonym_label": "СИНОНИМ",
        "learning_finish": "АЯКТОО",
        "learning_next_word": "КЕЛЕСКИ СӨЗ",
        "learning_flip_hint": "Картаны которуу үчүн ага басыңыз.",
        "loading_subtitle": "Сөздөр даярдалууда...",
        "cd_close": "Жабуу",
        "cd_add_word": "Сөз кошуу",
        "cd_settings": "Жөндөөлөр",
        "mode_hint_title": "Сөздүктү алмаштыра аласыз",
        "mode_hint_body": "Синонимдер, этишттер, макал-лакаптар жана башкалар ортосунда которулуңуз. Жергиликтүү базада жок сөздөр TDK-да автоматтык изделет.",
        "mode_hint_ok": "Түшündüm",
        "menu_show_daily_word": "Күн сөзүн көрсөтүү",
        "share_word_title": "Сөздү бөлүшүү",
        "word_tree_title": "СӨЗ ДАРАГЫ",
        "cd_reset": "Кайра орнотуу",
        "cd_favorite": "Тандалган",
        "cd_listen": "Угуу",
        "cd_share": "Бөлүшүү",
        "cd_speak": "Үн менен окуу",
        "cd_voice_search": "Үн издөө",
        "voice_search_prompt": "Сөз айтыңыз...",
        "weekly_last_7_days": "Акыркы 7 күн",
        "day_mon": "Дш",
        "day_tue": "Шш",
        "day_wed": "Шр",
        "day_thu": "Бш",
        "day_fri": "Жм",
        "day_sat": "Иш",
        "day_sun": "Жк",
        "day_mon_full": "Дүйшөмбү",
        "day_tue_full": "Шейшемби",
        "day_wed_full": "Шаршемби",
        "day_thu_full": "Бейшемби",
        "day_fri_full": "Жума",
        "day_sat_full": "Ишемби",
        "day_sun_full": "Жекшемби",
        "notification_channel_name": "Күн сөзү",
        "notification_title": "Күн сөзү: %1$s",
        "notification_body": "Синоним: %1$s. Азыр үйрөн!",
        "share_mode_verbs": "мааниси",
        "share_mode_definitions": "аныктamasы",
        "share_mode_idioms": "мааниси",
        "share_mode_adjectives": "мааниси",
        "share_mode_all": "мааниси/синоним"
    },
    "mr": {
        "favorites_title": "माझे आवडते",
        "search_short_placeholder": "शोध...",
        "btn_study": "अभ्यास",
        "cd_clear": "साफ करा",
        "favorites_empty_title": "अद्याप आवडते नाहीत",
        "favorites_empty_search_title": "निकाल सापडले नाहीत",
        "favorites_empty_desc": "आवडती शब्द येथे जोडा, नंतर अभ्यास करा.",
        "favorites_empty_search_desc": "तुमच्या शोधाशी जुळणारा आवडता शब्द सापडला नाही.",
        "cd_delete": "हटवा",
        "learning_no_favorites_title": "अद्याप आवडते नाहीत",
        "learning_no_favorites_message": "फ्लॅशकार्डसाठी शब्दकोशातून काही शब्द आवडते मध्ये जोडा.",
        "learning_cards_title": "फ्लॅशकार्ड",
        "learning_word_label": "शब्द",
        "learning_synonym_label": "समानार्थी",
        "learning_finish": "समाप्त",
        "learning_next_word": "पुढील शब्द",
        "learning_flip_hint": "कार्ड उलटवण्यासाठी त्यावर टॅप करा.",
        "loading_subtitle": "शब्द लोड होत आहेत...",
        "cd_close": "बंद",
        "cd_add_word": "शब्द जोडा",
        "cd_settings": "सेटिंग्ज",
        "mode_hint_title": "तुम्ही शब्दकोश बदलू शकता",
        "mode_hint_body": "समानार्थी, क्रियापद, वाक्प्रचार इ. दरम्यान स्विच करा. स्थानिक शोधात नसलेले शब्द TDK वर आपोआप शोधले जातात.",
        "mode_hint_ok": "समजले",
        "menu_show_daily_word": "आजचा शब्द दाखवा",
        "share_word_title": "शब्द शेअर करा",
        "word_tree_title": "शब्द वृक्ष",
        "cd_reset": "रीसेट",
        "cd_favorite": "आवडते",
        "cd_listen": "ऐका",
        "cd_share": "शेअर",
        "cd_speak": "मोठ्याने वाचा",
        "cd_voice_search": "व्हॉइस शोध",
        "voice_search_prompt": "एक शब्द बोला...",
        "weekly_last_7_days": "मागील 7 दिवस",
        "day_mon": "सोम",
        "day_tue": "मंग",
        "day_wed": "बुध",
        "day_thu": "गुरु",
        "day_fri": "शुक्र",
        "day_sat": "शनि",
        "day_sun": "रवि",
        "day_mon_full": "सोमवार",
        "day_tue_full": "मंगळवार",
        "day_wed_full": "बुधवार",
        "day_thu_full": "गुरुवार",
        "day_fri_full": "शुक्रवार",
        "day_sat_full": "शनिवार",
        "day_sun_full": "रविवार",
        "notification_channel_name": "आजचा शब्द",
        "notification_title": "आजचा शब्द: %1$s",
        "notification_body": "समानार्थी: %1$s. आत्ताच शिका!",
        "share_mode_verbs": "अर्थ",
        "share_mode_definitions": "व्याख्या",
        "share_mode_idioms": "अर्थ",
        "share_mode_adjectives": "अर्थ",
        "share_mode_all": "अर्थ/समानार्थी"
    },
    "pt": {
        "favorites_title": "MEUS FAVORITOS",
        "search_short_placeholder": "Pesquisar...",
        "btn_study": "ESTUDAR",
        "cd_clear": "Limpar",
        "favorites_empty_title": "Ainda sem favoritos",
        "favorites_empty_search_title": "Nenhum resultado",
        "favorites_empty_desc": "Adicione palavras que gosta aqui para estudar depois.",
        "favorites_empty_search_desc": "Nenhuma palavra favorita corresponde à sua pesquisa.",
        "cd_delete": "Excluir",
        "learning_no_favorites_title": "Ainda sem favoritos",
        "learning_no_favorites_message": "Adicione palavras aos favoritos no dicionário para usar os cartões.",
        "learning_cards_title": "Cartões",
        "learning_word_label": "PALAVRA",
        "learning_synonym_label": "SINÓNIMO",
        "learning_finish": "CONCLUIR",
        "learning_next_word": "PRÓXIMA PALAVRA",
        "learning_flip_hint": "Toque no cartão para virá-lo.",
        "loading_subtitle": "Carregando palavras...",
        "cd_close": "Fechar",
        "cd_add_word": "Adicionar palavra",
        "cd_settings": "Configurações",
        "mode_hint_title": "Você pode trocar de dicionário",
        "mode_hint_body": "Alterne entre sinónimos, verbos, expressões e mais. Palavras não encontradas localmente são pesquisadas no TDK automaticamente.",
        "mode_hint_ok": "Entendi",
        "menu_show_daily_word": "Mostrar palavra do dia",
        "share_word_title": "Partilhar palavra",
        "word_tree_title": "ÁRVORE DE PALAVRAS",
        "cd_reset": "Repor",
        "cd_favorite": "Favorito",
        "cd_listen": "Ouvir",
        "cd_share": "Partilhar",
        "cd_speak": "Ler em voz alta",
        "cd_voice_search": "Pesquisa por voz",
        "voice_search_prompt": "Diga uma palavra...",
        "weekly_last_7_days": "Últimos 7 dias",
        "day_mon": "Seg",
        "day_tue": "Ter",
        "day_wed": "Qua",
        "day_thu": "Qui",
        "day_fri": "Sex",
        "day_sat": "Sáb",
        "day_sun": "Dom",
        "day_mon_full": "Segunda-feira",
        "day_tue_full": "Terça-feira",
        "day_wed_full": "Quarta-feira",
        "day_thu_full": "Quinta-feira",
        "day_fri_full": "Sexta-feira",
        "day_sat_full": "Sábado",
        "day_sun_full": "Domingo",
        "notification_channel_name": "Palavra do dia",
        "notification_title": "Palavra do dia: %1$s",
        "notification_body": "Sinónimo: %1$s. Aprenda agora!",
        "share_mode_verbs": "significado",
        "share_mode_definitions": "definição",
        "share_mode_idioms": "significado",
        "share_mode_adjectives": "significado",
        "share_mode_all": "significado/sinónimo"
    },
    "ru": {
        "favorites_title": "ИЗБРАННОЕ",
        "search_short_placeholder": "Поиск...",
        "btn_study": "УЧИТЬ",
        "cd_clear": "Очистить",
        "favorites_empty_title": "Пока нет избранного",
        "favorites_empty_search_title": "Ничего не найдено",
        "favorites_empty_desc": "Добавляйте понравившиеся слова сюда, чтобы учить их позже.",
        "favorites_empty_search_desc": "Ни одно избранное слово не совпало с запросом.",
        "cd_delete": "Удалить",
        "learning_no_favorites_title": "Пока нет избранного",
        "learning_no_favorites_message": "Добавьте слова в избранное из словаря, чтобы использовать карточки.",
        "learning_cards_title": "Карточки",
        "learning_word_label": "СЛОВО",
        "learning_synonym_label": "СИНОНИМ",
        "learning_finish": "ГОТОВО",
        "learning_next_word": "СЛЕДУЮЩЕЕ СЛОВО",
        "learning_flip_hint": "Нажмите на карточку, чтобы перевернуть.",
        "loading_subtitle": "Загрузка слов...",
        "cd_close": "Закрыть",
        "cd_add_word": "Добавить слово",
        "cd_settings": "Настройки",
        "mode_hint_title": "Можно переключить словарь",
        "mode_hint_body": "Переключайтесь между синонимами, глаголами, идиомами и др. Слова, не найденные локально, ищутся в TDK автоматически.",
        "mode_hint_ok": "Понятно",
        "menu_show_daily_word": "Показать слово дня",
        "share_word_title": "Поделиться словом",
        "word_tree_title": "ДЕРЕВО СЛОВ",
        "cd_reset": "Сброс",
        "cd_favorite": "Избранное",
        "cd_listen": "Слушать",
        "cd_share": "Поделиться",
        "cd_speak": "Прочитать вслух",
        "cd_voice_search": "Голосовой поиск",
        "voice_search_prompt": "Произнесите слово...",
        "weekly_last_7_days": "Последние 7 дней",
        "day_mon": "Пн",
        "day_tue": "Вт",
        "day_wed": "Ср",
        "day_thu": "Чт",
        "day_fri": "Пт",
        "day_sat": "Сб",
        "day_sun": "Вс",
        "day_mon_full": "Понедельник",
        "day_tue_full": "Вторник",
        "day_wed_full": "Среда",
        "day_thu_full": "Четверг",
        "day_fri_full": "Пятница",
        "day_sat_full": "Суббота",
        "day_sun_full": "Воскресенье",
        "notification_channel_name": "Слово дня",
        "notification_title": "Слово дня: %1$s",
        "notification_body": "Синоним: %1$s. Учите сейчас!",
        "share_mode_verbs": "значение",
        "share_mode_definitions": "определение",
        "share_mode_idioms": "значение",
        "share_mode_adjectives": "значение",
        "share_mode_all": "значение/синоним"
    },
    "sw": {
        "favorites_title": "VIPENDWA VYANGU",
        "search_short_placeholder": "Tafuta...",
        "btn_study": "SOMA",
        "cd_clear": "Futa",
        "favorites_empty_title": "Bado hakuna vipendwa",
        "favorites_empty_search_title": "Hakuna matokeo",
        "favorites_empty_desc": "Ongeza maneno unayopenda hapa ili uyasome baadaye.",
        "favorites_empty_search_desc": "Hakuna neno pendwa linalolingana na utafutaji wako.",
        "cd_delete": "Futa",
        "learning_no_favorites_title": "Bado hakuna vipendwa",
        "learning_no_favorites_message": "Ongeza maneno kwenye vipendwa kutoka kamusi ili kutumia kadi.",
        "learning_cards_title": "Kadi za kujifunza",
        "learning_word_label": "NENO",
        "learning_synonym_label": "KISAWE",
        "learning_finish": "MALIZA",
        "learning_next_word": "NENO LIJALO",
        "learning_flip_hint": "Gusa kadi ili uigeuze.",
        "loading_subtitle": "Inapakia maneno...",
        "cd_close": "Funga",
        "cd_add_word": "Ongeza neno",
        "cd_settings": "Mipangilio",
        "mode_hint_title": "Unaweza kubadilisha kamusi",
        "mode_hint_body": "Badilisha kati ya visawe, vitenzi, methali na zaidi. Maneno yasiyopatikana ndani hutafutwa kwenye TDK kiotomatiki.",
        "mode_hint_ok": "Nimeelewa",
        "menu_show_daily_word": "Onyesha neno la leo",
        "share_word_title": "Shiriki neno",
        "word_tree_title": "MTI WA MANENO",
        "cd_reset": "Weka upya",
        "cd_favorite": "Pendwa",
        "cd_listen": "Sikiliza",
        "cd_share": "Shiriki",
        "cd_speak": "Soma kwa sauti",
        "cd_voice_search": "Utafutaji wa sauti",
        "voice_search_prompt": "Sema neno...",
        "weekly_last_7_days": "Siku 7 zilizopita",
        "day_mon": "Jtt",
        "day_tue": "Jnn",
        "day_wed": "Jtn",
        "day_thu": "Alh",
        "day_fri": "Ijm",
        "day_sat": "Jms",
        "day_sun": "Jpl",
        "day_mon_full": "Jumatatu",
        "day_tue_full": "Jumanne",
        "day_wed_full": "Jumatano",
        "day_thu_full": "Alhamisi",
        "day_fri_full": "Ijumaa",
        "day_sat_full": "Jumamosi",
        "day_sun_full": "Jumapili",
        "notification_channel_name": "Neno la leo",
        "notification_title": "Neno la leo: %1$s",
        "notification_body": "Kisawe: %1$s. Jifunze sasa!",
        "share_mode_verbs": "maana",
        "share_mode_definitions": "ufafanuzi",
        "share_mode_idioms": "maana",
        "share_mode_adjectives": "maana",
        "share_mode_all": "maana/kisawe"
    },
    "ta": {
        "favorites_title": "என் பிடித்தவை",
        "search_short_placeholder": "தேடு...",
        "btn_study": "படி",
        "cd_clear": "அழி",
        "favorites_empty_title": "இன்னும் பிடித்தவை இல்லை",
        "favorites_empty_search_title": "முடிவுகள் இல்லை",
        "favorites_empty_desc": "பிடித்த சொற்களை இங்கே சேர்த்து பின்னர் படிக்கலாம்.",
        "favorites_empty_search_desc": "உங்கள் தேடலுடன் பொருந்தும் பிடித்த சொல் இல்லை.",
        "cd_delete": "நீக்கு",
        "learning_no_favorites_title": "இன்னும் பிடித்தவை இல்லை",
        "learning_no_favorites_message": "ஃபிளாஷ் கார்டுகளுக்கு அகராதியிலிருந்து சொற்களை பிடித்தவையில் சேர்க்கவும்.",
        "learning_cards_title": "ஃபிளாஷ் கார்டுகள்",
        "learning_word_label": "சொல்",
        "learning_synonym_label": "ஒத்த சொல்",
        "learning_finish": "முடி",
        "learning_next_word": "அடுத்த சொல்",
        "learning_flip_hint": "அட்டையை திருப்ப தட்டவும்.",
        "loading_subtitle": "சொற்கள் ஏற்றப்படுகின்றன...",
        "cd_close": "மூடு",
        "cd_add_word": "சொல் சேர்",
        "cd_settings": "அமைப்புகள்",
        "mode_hint_title": "நீங்கள் அகராதியை மாற்றலாம்",
        "mode_hint_body": "ஒத்த சொற்கள், வினைச்சொற்கள், பழமொழிகள் மற்றும் பலவற்றுக்கு இடையே மாற்றவும். உள்ளூரில் இல்லாத சொற்கள் TDK-இல் தானாக தேடப்படும்.",
        "mode_hint_ok": "புரிந்தது",
        "menu_show_daily_word": "இன்றைய சொல்லை காட்டு",
        "share_word_title": "சொல்லை பகிர்",
        "word_tree_title": "சொல் மரம்",
        "cd_reset": "மீட்டமை",
        "cd_favorite": "பிடித்தது",
        "cd_listen": "கேள்",
        "cd_share": "பகிர்",
        "cd_speak": "சத்தமாக படி",
        "cd_voice_search": "குரல் தேடல்",
        "voice_search_prompt": "ஒரு சொல்லை சொல்லுங்கள்...",
        "weekly_last_7_days": "கடந்த 7 நாட்கள்",
        "day_mon": "தி",
        "day_tue": "செ",
        "day_wed": "பு",
        "day_thu": "வி",
        "day_fri": "வெ",
        "day_sat": "ச",
        "day_sun": "ஞா",
        "day_mon_full": "திங்கள்",
        "day_tue_full": "செவ்வாய்",
        "day_wed_full": "புதன்",
        "day_thu_full": "வியாழன்",
        "day_fri_full": "வெள்ளி",
        "day_sat_full": "சனி",
        "day_sun_full": "ஞாயிறு",
        "notification_channel_name": "இன்றைய சொல்",
        "notification_title": "இன்றைய சொல்: %1$s",
        "notification_body": "ஒத்த சொல்: %1$s. இப்போது கற்றுக்கொள்ளுங்கள்!",
        "share_mode_verbs": "பொருள்",
        "share_mode_definitions": "வரையிலை",
        "share_mode_idioms": "பொருள்",
        "share_mode_adjectives": "பொருள்",
        "share_mode_all": "பொருள்/ஒத்த சொல்"
    },
    "te": {
        "favorites_title": "నా ఇష్టమైనవి",
        "search_short_placeholder": "వెతకండి...",
        "btn_study": "చదువు",
        "cd_clear": "తొలగించు",
        "favorites_empty_title": "ఇంకా ఇష్టమైనవి లేవు",
        "favorites_empty_search_title": "ఫలితాలు లేవు",
        "favorites_empty_desc": "మీకు నచ్చిన పదాలను ఇక్కడ జోడించి, తర్వాత నేర్చుకోండి.",
        "favorites_empty_search_desc": "మీ శోధనకు సరిపడే ఇష్టమైన పదం లేదు.",
        "cd_delete": "తొలగించు",
        "learning_no_favorites_title": "ఇంకా ఇష్టమైనవి లేవు",
        "learning_no_favorites_message": "కార్డుల కోసం ముందుగా నిఘంటువు నుండి పదాలను ఇష్టమైనవికి జోడించండి.",
        "learning_cards_title": "ఫ్లాష్ కార్డులు",
        "learning_word_label": "పదం",
        "learning_synonym_label": "పర్యాయపదం",
        "learning_finish": "ముగించు",
        "learning_next_word": "తదుపరి పదం",
        "learning_flip_hint": "కార్డును తిప్పడానికి దానిపై ట్యాప్ చేయండి.",
        "loading_subtitle": "పదాలు లోడ్ అవుతున్నాయి...",
        "cd_close": "మూసివేయి",
        "cd_add_word": "పదం జోడించు",
        "cd_settings": "సెట్టింగ్‌లు",
        "mode_hint_title": "మీరు నిఘంటువును మార్చవచ్చు",
        "mode_hint_body": "పర్యాయపదాలు, క్రీయలు, సామెతలు మధ్య మారండి. స్థానీకంగా లేని పదాలు TDKలో స్వయంచాలకంగా వెతకబడతాయి.",
        "mode_hint_ok": "అర్థమైంది",
        "menu_show_daily_word": "నేటి పదం చూపించు",
        "share_word_title": "పదం షేర్ చేయి",
        "word_tree_title": "పద వృక్షం",
        "cd_reset": "రీసెట్",
        "cd_favorite": "ఇష్టం",
        "cd_listen": "వినండి",
        "cd_share": "షేర్",
        "cd_speak": "గట్టిగా చదవండి",
        "cd_voice_search": "వాయిస్ శోధన",
        "voice_search_prompt": "ఒక పదం చెప్పండి...",
        "weekly_last_7_days": "గత 7 రోజులు",
        "day_mon": "సో",
        "day_tue": "మం",
        "day_wed": "బు",
        "day_thu": "గు",
        "day_fri": "శు",
        "day_sat": "శ",
        "day_sun": "ఆ",
        "day_mon_full": "సోమవారం",
        "day_tue_full": "మంగళవారం",
        "day_wed_full": "బుధవారం",
        "day_thu_full": "గురువారం",
        "day_fri_full": "శుక్రవారం",
        "day_sat_full": "శనివారం",
        "day_sun_full": "ఆదివారం",
        "notification_channel_name": "నేటి పదం",
        "notification_title": "నేటి పదం: %1$s",
        "notification_body": "పర్యాయపదం: %1$s. ఇప్పుడే నేర్చుకోండి!",
        "share_mode_verbs": "అర్థం",
        "share_mode_definitions": "నిర్వచనం",
        "share_mode_idioms": "అర్థం",
        "share_mode_adjectives": "అర్థం",
        "share_mode_all": "అర్థం/పర్యాయపదం"
    },
    "tk": {
        "favorites_title": "SAÝLANANLARYM",
        "search_short_placeholder": "Gözle...",
        "btn_study": "ÖWREN",
        "cd_clear": "Arassala",
        "favorites_empty_title": "Entek saýlanan ýok",
        "favorites_empty_search_title": "Netije tapylmady",
        "favorites_empty_desc": "Halaýan sözleriňizi şu ýere goşup, soň öwrenip bilersiňiz.",
        "favorites_empty_search_desc": "Gözlegiňize laýyk saýlanan söz tapylmady.",
        "cd_delete": "Poz",
        "learning_no_favorites_title": "Entek saýlanan ýok",
        "learning_no_favorites_message": "Kartlary ulanmak üçin ilki sözlükden käbir sözleri saýlananlara goşuň.",
        "learning_cards_title": "Söz kartlary",
        "learning_word_label": "SÖZ",
        "learning_synonym_label": "SINONIM",
        "learning_finish": "TAMAMLA",
        "learning_next_word": "INDIKI SÖZ",
        "learning_flip_hint": "Karty öwürmek üçin basyň.",
        "loading_subtitle": "Sözler taýýarlanýar...",
        "cd_close": "Ýap",
        "cd_add_word": "Söz goş",
        "cd_settings": "Sazlamalar",
        "mode_hint_title": "Sözlügi çalyşyp bilersiňiz",
        "mode_hint_body": "Sinonimler, feiller, makallar we ş.m. arasynda geçiň. Ýerli bazada bolmadyk sözler awtomatik TDK-da gözlenilýär.",
        "mode_hint_ok": "Düşündim",
        "menu_show_daily_word": "Günüň sözünü görkez",
        "share_word_title": "Sözi paýlaş",
        "word_tree_title": "SÖZ AGACI",
        "cd_reset": "Täzeden başla",
        "cd_favorite": "Saýlanan",
        "cd_listen": "Diňle",
        "cd_share": "Paýlaş",
        "cd_speak": "Sesli oka",
        "cd_voice_search": "Sesli gözleg",
        "voice_search_prompt": "Bir söz aýdyň...",
        "weekly_last_7_days": "Soňky 7 gün",
        "day_mon": "Du",
        "day_tue": "Si",
        "day_wed": "Ça",
        "day_thu": "Pe",
        "day_fri": "An",
        "day_sat": "Şe",
        "day_sun": "Ýe",
        "day_mon_full": "Duşenbe",
        "day_tue_full": "Sişenbe",
        "day_wed_full": "Çarşenbe",
        "day_thu_full": "Penşenbe",
        "day_fri_full": "Anna",
        "day_sat_full": "Şenbe",
        "day_sun_full": "Ýekşenbe",
        "notification_channel_name": "Günüň sözi",
        "notification_title": "Günüň sözi: %1$s",
        "notification_body": "Sinonim: %1$s. Häzir öwren!",
        "share_mode_verbs": "many",
        "share_mode_definitions": "düşündiriş",
        "share_mode_idioms": "many",
        "share_mode_adjectives": "many",
        "share_mode_all": "many/sinonim"
    },
    "ur": {
        "favorites_title": "میری پسندیدہ",
        "search_short_placeholder": "تلاش...",
        "btn_study": "مطالعہ",
        "cd_clear": "صاف کریں",
        "favorites_empty_title": "ابھی کوئی پسندیدہ نہیں",
        "favorites_empty_search_title": "کوئی نتیجہ نہیں",
        "favorites_empty_desc": "پسندیدہ الفاظ یہاں شامل کریں تاکہ بعد میں پڑھ سکیں۔",
        "favorites_empty_search_desc": "آپ کی تلاش سے کوئی پسندیدہ لفظ مماثل نہیں۔",
        "cd_delete": "حذف",
        "learning_no_favorites_title": "ابھی کوئی پسندیدہ نہیں",
        "learning_no_favorites_message": "فلیش کارڈز کے لیے لغت سے کچھ الفاظ پسندیدہ میں شامل کریں۔",
        "learning_cards_title": "فلیش کارڈز",
        "learning_word_label": "لفظ",
        "learning_synonym_label": "مترادف",
        "learning_finish": "ختم",
        "learning_next_word": "اگلا لفظ",
        "learning_flip_hint": "کارڈ پلٹنے کے لیے اسے تھپتھپائیں۔",
        "loading_subtitle": "الفاظ لوڈ ہو رہے ہیں...",
        "cd_close": "بند",
        "cd_add_word": "لفظ شامل کریں",
        "cd_settings": "ترتیبات",
        "mode_hint_title": "آپ لغت تبدیل کر سکتے ہیں",
        "mode_hint_body": "مترادفات، فعل، محاورے وغیرہ کے درمیان تبدیل کریں۔ مقامی طور پر نہ ملنے والے الفاظ TDK میں خودکار تلاش ہوتے ہیں۔",
        "mode_hint_ok": "سمجھ گیا",
        "menu_show_daily_word": "آج کا لفظ دکھائیں",
        "share_word_title": "لفظ شیئر کریں",
        "word_tree_title": "لفظ کا درخت",
        "cd_reset": "ری سیٹ",
        "cd_favorite": "پسندیدہ",
        "cd_listen": "سنیں",
        "cd_share": "شیئر",
        "cd_speak": "بلند آواز میں پڑھیں",
        "cd_voice_search": "آواز سے تلاش",
        "voice_search_prompt": "ایک لفظ بولیں...",
        "weekly_last_7_days": "گزشتہ 7 دن",
        "day_mon": "پیر",
        "day_tue": "منگل",
        "day_wed": "بدھ",
        "day_thu": "جمعرات",
        "day_fri": "جمعہ",
        "day_sat": "ہفتہ",
        "day_sun": "اتوار",
        "day_mon_full": "پیر",
        "day_tue_full": "منگل",
        "day_wed_full": "بدھ",
        "day_thu_full": "جمعرات",
        "day_fri_full": "جمعہ",
        "day_sat_full": "ہفتہ",
        "day_sun_full": "اتوار",
        "notification_channel_name": "آج کا لفظ",
        "notification_title": "آج کا لفظ: %1$s",
        "notification_body": "مترادف: %1$s. ابھی سیکھیں!",
        "share_mode_verbs": "معنی",
        "share_mode_definitions": "تعریف",
        "share_mode_idioms": "معنی",
        "share_mode_adjectives": "معنی",
        "share_mode_all": "معنی/مترادف"
    },
    "uz": {
        "favorites_title": "TANLANGANLARIM",
        "search_short_placeholder": "Qidirish...",
        "btn_study": "O'RGANISH",
        "cd_clear": "Tozalash",
        "favorites_empty_title": "Hali tanlangan yo'q",
        "favorites_empty_search_title": "Natija topilmadi",
        "favorites_empty_desc": "Yoqtirgan so'zlaringizni bu yerga qo'shib, keyin o'rganing.",
        "favorites_empty_search_desc": "Qidiruvingizga mos tanlangan so'z topilmadi.",
        "cd_delete": "O'chirish",
        "learning_no_favorites_title": "Hali tanlangan yo'q",
        "learning_no_favorites_message": "Kartochkalardan foydalanish uchun avval lug'atdan so'zlarni tanlanganlarga qo'shing.",
        "learning_cards_title": "So'z kartochkalari",
        "learning_word_label": "SO'Z",
        "learning_synonym_label": "SINONIM",
        "learning_finish": "TUGATISH",
        "learning_next_word": "KEYINGI SO'Z",
        "learning_flip_hint": "Kartochkani aylantirish uchun ustiga bosing.",
        "loading_subtitle": "So'zlar tayyorlanmoqda...",
        "cd_close": "Yopish",
        "cd_add_word": "So'z qo'shish",
        "cd_settings": "Sozlamalar",
        "mode_hint_title": "Lug'atni almashtirishingiz mumkin",
        "mode_hint_body": "Sinonimlar, fe'llar, maqollar va boshqalar o'rtasida o'ting. Mahalliy bazada bo'lmagan so'zlar TDK-da avtomatik qidiriladi.",
        "mode_hint_ok": "Tushundim",
        "menu_show_daily_word": "Kun so'zini ko'rsatish",
        "share_word_title": "So'zni ulashish",
        "word_tree_title": "SO'Z DARAXTI",
        "cd_reset": "Qayta o'rnatish",
        "cd_favorite": "Tanlangan",
        "cd_listen": "Tinglash",
        "cd_share": "Ulashish",
        "cd_speak": "Ovozli o'qish",
        "cd_voice_search": "Ovozli qidiruv",
        "voice_search_prompt": "So'z ayting...",
        "weekly_last_7_days": "So'nggi 7 kun",
        "day_mon": "Du",
        "day_tue": "Se",
        "day_wed": "Chor",
        "day_thu": "Pay",
        "day_fri": "Ju",
        "day_sat": "Shan",
        "day_sun": "Yak",
        "day_mon_full": "Dushanba",
        "day_tue_full": "Seshanba",
        "day_wed_full": "Chorshanba",
        "day_thu_full": "Payshanba",
        "day_fri_full": "Juma",
        "day_sat_full": "Shanba",
        "day_sun_full": "Yakshanba",
        "notification_channel_name": "Kun so'zi",
        "notification_title": "Kun so'zi: %1$s",
        "notification_body": "Sinonim: %1$s. Hozir o'rganing!",
        "share_mode_verbs": "ma'nosi",
        "share_mode_definitions": "ta'rifi",
        "share_mode_idioms": "ma'nosi",
        "share_mode_adjectives": "ma'nosi",
        "share_mode_all": "ma'nosi/sinonim"
    },
    "vi": {
        "favorites_title": "YÊU THÍCH CỦA TÔI",
        "search_short_placeholder": "Tìm...",
        "btn_study": "HỌC",
        "cd_clear": "Xóa",
        "favorites_empty_title": "Chưa có mục yêu thích",
        "favorites_empty_search_title": "Không có kết quả",
        "favorites_empty_desc": "Thêm từ bạn thích vào đây để học sau.",
        "favorites_empty_search_desc": "Không có từ yêu thích nào khớp với tìm kiếm của bạn.",
        "cd_delete": "Xóa",
        "learning_no_favorites_title": "Chưa có mục yêu thích",
        "learning_no_favorites_message": "Thêm từ vào yêu thích từ từ điển để dùng thẻ ghi nhớ.",
        "learning_cards_title": "Thẻ ghi nhớ",
        "learning_word_label": "TỪ",
        "learning_synonym_label": "TỪ ĐỒNG NGHĨA",
        "learning_finish": "HOÀN TẤT",
        "learning_next_word": "TỪ TIẾP THEO",
        "learning_flip_hint": "Chạm vào thẻ để lật.",
        "loading_subtitle": "Đang tải từ...",
        "cd_close": "Đóng",
        "cd_add_word": "Thêm từ",
        "cd_settings": "Cài đặt",
        "mode_hint_title": "Bạn có thể đổi từ điển",
        "mode_hint_body": "Chuyển giữa từ đồng nghĩa, động từ, thành ngữ và hơn nữa. Từ không có cục bộ sẽ được tìm trên TDK tự động.",
        "mode_hint_ok": "Đã hiểu",
        "menu_show_daily_word": "Hiện từ trong ngày",
        "share_word_title": "Chia sẻ từ",
        "word_tree_title": "CÂY TỪ",
        "cd_reset": "Đặt lại",
        "cd_favorite": "Yêu thích",
        "cd_listen": "Nghe",
        "cd_share": "Chia sẻ",
        "cd_speak": "Đọc to",
        "cd_voice_search": "Tìm bằng giọng nói",
        "voice_search_prompt": "Nói một từ...",
        "weekly_last_7_days": "7 ngày qua",
        "day_mon": "T2",
        "day_tue": "T3",
        "day_wed": "T4",
        "day_thu": "T5",
        "day_fri": "T6",
        "day_sat": "T7",
        "day_sun": "CN",
        "day_mon_full": "Thứ Hai",
        "day_tue_full": "Thứ Ba",
        "day_wed_full": "Thứ Tư",
        "day_thu_full": "Thứ Năm",
        "day_fri_full": "Thứ Sáu",
        "day_sat_full": "Thứ Bảy",
        "day_sun_full": "Chủ Nhật",
        "notification_channel_name": "Từ trong ngày",
        "notification_title": "Từ trong ngày: %1$s",
        "notification_body": "Từ đồng nghĩa: %1$s. Học ngay!",
        "share_mode_verbs": "nghĩa",
        "share_mode_definitions": "định nghĩa",
        "share_mode_idioms": "nghĩa",
        "share_mode_adjectives": "nghĩa",
        "share_mode_all": "nghĩa/từ đồng nghĩa"
    },
    "zh-CN": {
        "favorites_title": "我的收藏",
        "search_short_placeholder": "搜索...",
        "btn_study": "学习",
        "cd_clear": "清除",
        "favorites_empty_title": "暂无收藏",
        "favorites_empty_search_title": "未找到结果",
        "favorites_empty_desc": "将喜欢的单词添加到这里，稍后学习。",
        "favorites_empty_search_desc": "没有与您搜索匹配的收藏单词。",
        "cd_delete": "删除",
        "learning_no_favorites_title": "暂无收藏",
        "learning_no_favorites_message": "请先从词典中将单词添加到收藏，以使用闪卡。",
        "learning_cards_title": "闪卡",
        "learning_word_label": "单词",
        "learning_synonym_label": "同义词",
        "learning_finish": "完成",
        "learning_next_word": "下一个单词",
        "learning_flip_hint": "点击卡片翻转。",
        "loading_subtitle": "正在加载单词...",
        "cd_close": "关闭",
        "cd_add_word": "添加单词",
        "cd_settings": "设置",
        "mode_hint_title": "您可以切换词典",
        "mode_hint_body": "在同义词、动词、习语等之间切换。本地未找到的单词会自动在 TDK 中搜索。",
        "mode_hint_ok": "知道了",
        "menu_show_daily_word": "显示每日一词",
        "share_word_title": "分享单词",
        "word_tree_title": "单词树",
        "cd_reset": "重置",
        "cd_favorite": "收藏",
        "cd_listen": "收听",
        "cd_share": "分享",
        "cd_speak": "朗读",
        "cd_voice_search": "语音搜索",
        "voice_search_prompt": "说一个单词...",
        "weekly_last_7_days": "最近7天",
        "day_mon": "周一",
        "day_tue": "周二",
        "day_wed": "周三",
        "day_thu": "周四",
        "day_fri": "周五",
        "day_sat": "周六",
        "day_sun": "周日",
        "day_mon_full": "星期一",
        "day_tue_full": "星期二",
        "day_wed_full": "星期三",
        "day_thu_full": "星期四",
        "day_fri_full": "星期五",
        "day_sat_full": "星期六",
        "day_sun_full": "星期日",
        "notification_channel_name": "每日一词",
        "notification_title": "每日一词：%1$s",
        "notification_body": "同义词：%1$s。立即学习！",
        "share_mode_verbs": "含义",
        "share_mode_definitions": "定义",
        "share_mode_idioms": "含义",
        "share_mode_adjectives": "含义",
        "share_mode_all": "含义/同义词"
    }
}

_PATCH_KEYS = set(NEW_EN.keys())
for _code, _patch in LOCALE_PATCHES.items():
    if set(_patch.keys()) != _PATCH_KEYS:
        raise ValueError(f"Locale {_code!r} must have exactly {len(_PATCH_KEYS)} patch keys")
